#version: '3.1'
#volumes:
#  data:
#    driver: local
#networks:
#  network-backend:
#    driver: bridge
#services:
#  mongoDb:
#    image: mongo:latest
#    command: --serviceExecutor adaptive
#    container_name: mongodb
#    restart: always
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: 123
#    ports:
#      - 27017:27017
#  mongo-express:
#    image: mongo-express
#    restart: always
#    ports:
#      - 8081:8081
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: 123
#
#  ctferro-api-image:
#    image: ctferro-api-image
#    container_name: ctferro-api-image
#    ports:
#      - 8080:8080
#    links:
#      - mongoDb
#
