spring:
  data:
    mongodb:
      host: '${secrets.MONGO_HOST:localhost}'
      port: 27017
      database: '${secrets.MONGO_DB:ctferrodb}'

  cloud:
    kubernetes:
      discovery:
        register: true

      config:
        enabled: true
        sources:
          - namespace: default
            name: ctferro-db-config
      reload:
        enabled: true
        mode: polling
        period: 1000