name: ctferro-api

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
#      - run: java Main.java

      - name: Build Java
        run: mvn clean install -DskipTests
      - name: Login Docker Hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p '${{secrets.DOCKER_PASSWORD}}'
      - name: Build docker image
        run: docker build -t alissoncruzsi/deploy-ctferro-api .
      - name: Push image docker
        run: docker push alissoncruzsi/deploy-ctferro-api
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull alissoncruzsi/deploy-ctferro-api:latest
      - name: Remove docker container
        run: docker rm -f deploy-ctferro-api
      - name: Run docker container
        run: docker run -d -p 8080:8080 -e DATABASE_URI=${{secrets.MONGO_HOST}} -e DATABASE_NAME=${{secrets.MONGO_DB}} --name deploy-ctferro-api alissoncruzsi/deploy-ctferro-api


